name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  RUST_VERSION: 1.68.2
  SOLC_CACHE_PATH: ${{ github.workspace }}/.solc_cache
  FUEL_CACHE_PATH: ${{ github.workspace }}/.fuel_cache

jobs:
  build-contracts:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project:
          [
            "01-hello-world",
            "02-counter",
            "03-logging",
            "04-storage",
            "05-conditional",
            "06-structs",
            "07-errors",
            "08-functions",
            "09-amounts",
            "10-message-info",
            "11-gas-info",
            "12-contract-info",
            "13-block-info",
            "14-transfer",
            "15-mint-tokens",
            "16-hashing",
            "17-ec-recover",
            "18-reentrancy-guard",
            "19-unsigned-integers",
            "20-contract-calls",
          ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup solc cache
        uses: actions/cache@v2
        with:
          path: ${{ env.SOLC_CACHE_PATH }}
          key: solc-cache

      - name: Install Solidity Compiler
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc
          mkdir -p ${{ env.SOLC_CACHE_PATH }}
          cp $(which solc) ${{ env.SOLC_CACHE_PATH }}/solc

      - name: Add solc to PATH
        run: echo "${{ env.SOLC_CACHE_PATH }}:${GITHUB_PATH}" >> $GITHUB_PATH

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Init cache
        uses: Swatinem/rust-cache@v2

      - name: Setup fuel cache
        uses: actions/cache@v2
        with:
          path: ${{ env.FUEL_CACHE_PATH }}
          key: fuel-cache

      - name: Install Fuel toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://install.fuel.network/fuelup-init.sh | sh
          mkdir -p ${{ env.FUEL_CACHE_PATH }}
          cp -r $HOME/.fuelup/bin ${{ env.FUEL_CACHE_PATH }}/bin

      - name: Add fuel to PATH
        run: echo "${{ env.FUEL_CACHE_PATH }}/bin:${GITHUB_PATH}" >> $GITHUB_PATH

      - name: Check Sway formatting
        run: |
          forc fmt --check ./${{ matrix.project }}/sway/src/*.sw

      - name: Build Sway
        run: |
          forc build --path ./${{ matrix.project }}/sway

      - name: Build Solidity
        run: |
          solc ./${{ matrix.project }}/solidity/*.sol
