name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  RUST_VERSION: 1.68.2

jobs:
  build-contracts:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project:
          [
            "01-hello-world",
          ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Init cache
        uses: Swatinem/rust-cache@v2

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: latest
          date: 2023-04-12
      
      - name: Build Sway
        run: |
          cd ${{ matrix.project }}/sway
          forc build --locked
